version: '3.8'

services:
  qwen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model_cache:/app/model_cache
      - ./static:/app/static
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - VECTOR_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  autogen:
    build:
      context: .
      dockerfile: Dockerfile
    command: python autogen_provider.py
    ports:
      - "8001:8001"
    volumes:
      - ./model_cache:/app/model_cache
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - VECTOR_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: mongod --setParameter "enableSearchIndex=true"
    environment:
      - MONGO_INITDB_DATABASE=shared_vectors
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
  mongodb_config:
