### model
model_name_or_path: Qwen/Qwen2.5-Coder-32B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: rust_dataset
template: sharegpt
cutoff_len: 2048
preprocessing_num_workers: 16

### output
output_dir: output/rust_finetune
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
quantization_bit: 4
rope_scaling: dynamic
flash_attn: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
